spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    # ImMemory
    url: jdbc:h2:mem:restaurant-voting
    # tcp: jdbc:h2:tcp://localhost:9092/mem:restaurant-voting
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    serialization:
      write-dates-as-timestamps: false
    date-format: HH:mm:ss


logging:
  level:
    root: WARN
    ru.javaops.restaurantvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.orm.jpa: DEBUG
#    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true